### ISSUE TITLE
timetick扱いの整理

### ISSUE THREAD

**Issue by HirokiIshiguro** [renesas/azure-rtos#3]
■課題
以下サンプルのようにtimetickが100Hz固定になっている。（R_CMT_CreatePeriodic()の第1引数は単位Hzの周期起動関数を生成するAPI)
https://github.com/azure-rtos/getting-started/blob/1e7a680fad910045c08b17934f394428ed6fdb14/Renesas/RSK_RX65N_2MB/app/board_init.c#L32

■対策
TX_TIMER_TICKS_PER_SECONDの定義を以下に追加する。
(1) https://github.com/azure-rtos/threadx/blob/master/ports/rxv2/ccrx/inc/tx_port.h
 -> rxv1やrxv3にも同じファイルがあるのでまとめて追加する
(2) https://github.com/azure-rtos/getting-started/blob/master/Renesas/RSK_RX65N_2MB/lib/threadx/tx_user.h
 -> 他のボード用のgetting-startedにも同じファイルがあるのでまとめて追加する

さらに、スマートコンフィグレータでtx_user.hのファイルを調整できるようにすると良いだろう。

**Comment by TakeoTakahashi2020** [comment]
スマートコンフィグレータの検討依頼をだしました。

**Comment by HirokiIshiguro** [comment]
@TakeoTakahashi2020 ありがとうございます。e2 studioでAzure RTOSプロジェクトを生成する機構においては修正計画が立てられました。本家への修正について今後検討させてください。

**Comment by HirokiIshiguro** [comment]
修正すべきコード：
https://github.com/azure-rtos/getting-started/blob/c913de75a9552d8c1ea29c93c87f0628d7387742/Renesas/RSK_RX65N_2MB/app/board_init.c#L32

こちらのサンプルも対象：
https://github.com/azure-rtos/samples
　→ただしこちらはe2 studioから出力できる機構が整理できたら、サンプル自体のアップが不要になると思われる。

**Comment by HirokiIshiguro** [comment]
本家にて修正完了確認。
https://github.com/azure-rtos/getting-started/commit/cfceb7e16cd3edc50fa0281592a192a9a1e6b436
